/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DreamAnalysisModal: typeof import('./src/components/dream/components/DreamAnalysisModal.vue')['default']
    DreamForm: typeof import('./src/components/dream/components/DreamForm.vue')['default']
    DreamHall: typeof import('./src/components/dream/DreamHall.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MyDream: typeof import('./src/components/dream/MyDream.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserDropdown: typeof import('./src/components/UserDropdown.vue')['default']
  }
}
